[package]
name = "proto"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
name = "proto"
path = "src/lib.rs"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
url = { version = "2.0.0", features = ["serde"] }

